name: GitForces Sync

on:
  workflow_dispatch:

jobs:
  execute-sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - name: Run Script
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          CF_KEY: ${{ secrets.CF_KEY }}
          CF_SECRET: ${{ secrets.CF_SECRET }}
          CF_HANDLE: ${{ secrets.CF_HANDLE }}
          GH_USER: ${{ secrets.GH_USER }}
          ARCHIVE_REPO: ${{ secrets.ARCHIVE_REPO }}
        run: python sync_codeforces.py
