name: GitForces Sync

on:
  workflow_dispatch:

jobs:
  execute-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requests
        run: pip install requests

      - name: Run Script
        env:
          CF_KEY: ${{ secrets.CF_KEY }}
          CF_SECRET: ${{ secrets.CF_SECRET }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: python sync_codeforces.py
